import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Clock3, FileVideo, Scale, Share2, Users } from "lucide-react";
import { getChallenge } from "@/lib/demo-data";
import { Countdown } from "@/components/countdown";

const fmt=(date:string)=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZoneName:"short"}).format(new Date(date));
export default async function ChallengePage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const challenge=getChallenge(slug); if(!challenge) notFound();
  return <div className="page">
    <header className="challenge-mast"><div style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><span className={`status ${challenge.state==="UPCOMING"?"upcoming":""}`}>{challenge.state}</span><button className="icon-button" aria-label="Share invitation link"><Share2 size={18}/></button></div><div className="challenge-index">#{challenge.number}</div><p className="eyebrow">Challenge drop</p><h1 className="display-md" style={{maxWidth:950}}>{challenge.title}</h1><p className="lede">{challenge.brief}</p></header>
    <div className="challenge-layout">
      <div><section><p className="eyebrow">The brief</p><p style={{fontSize:"clamp(1.35rem,3vw,2.1rem)",lineHeight:1.22,fontWeight:600}}>{challenge.description}</p></section><hr className="rule"/><section><div className="section-head"><h2>Non-negotiables</h2><span className="stamp">Same for everyone</span></div><ol className="rule-list">{challenge.rules.map(rule=><li key={rule}>{rule}</li>)}</ol></section><section><div className="section-head"><h2>Judged on</h2></div><div className="challenge-grid">{challenge.judgingDimensions.map((dimension,index)=><div className="panel panel-pad" key={dimension}><strong style={{font:"900 2.5rem var(--display)",color:"var(--blue)"}}>0{index+1}</strong><h3 style={{font:"800 1.5rem var(--display)",margin:"5px 0"}}>{dimension}</h3><p className="muted" style={{fontSize:12,margin:0}}>{index===0?"A fresh idea or surprising point of view.":index===1?"Craft, clarity and control of the chosen form.":"How powerfully the entry holds attention."}</p></div>)}</div></section></div>
      <aside><div className="panel panel-pad"><p className="field-label"><Clock3 size={15}/> Submission closes in</p><Countdown to={challenge.submissionClosesAt}/><div className="date-grid" style={{marginTop:15}}><div><small>Opens</small><strong>{fmt(challenge.opensAt)}</strong></div><div><small>Submit by</small><strong>{fmt(challenge.submissionClosesAt)}</strong></div><div><small>Reveal</small><strong>{fmt(challenge.revealOpensAt)}</strong></div><div><small>Results</small><strong>{fmt(challenge.settlesAt)}</strong></div></div></div><div className="panel panel-pad" style={{marginTop:12}}><p className="field-label"><FileVideo size={15}/> Media limits</p><p style={{fontWeight:700}}>MP4, WebM or MOV<br/>Up to {challenge.maxDurationSeconds}s · {Math.round(challenge.maxBytes/1_000_000)} MB</p><p className="muted" style={{fontSize:12}}>Captions are strongly encouraged. AI-generated media must be disclosed.</p></div><div className="panel panel-pad" style={{marginTop:12}}><p className="field-label"><Scale size={15}/> Your rights</p><p style={{fontSize:12,lineHeight:1.5}}>You keep ownership. SHOWOUT receives a narrow, non-exclusive licence to host, moderate and showcase this entry for this challenge. Terms v1.1.</p></div><button className="button full" style={{marginTop:12}}><Users size={17}/> Form a team</button><div className="sticky-action"><Link href={`/challenge/${challenge.slug}/submit`} className={`button full ${challenge.state==="OPEN"?"primary":""}`} aria-disabled={challenge.state!=="OPEN"}>{challenge.state==="OPEN"?"Enter Challenge":"Opens soon"}<ArrowRight size={17}/></Link></div></aside>
    </div>
  </div>;
}
