import Link from "next/link";
import { ArrowRight, Radio, Trophy } from "lucide-react";

const schedule=[
  ["NOW","REVEAL LIVE","Challenge #041 — THE PERFECT LOOP.","52 anonymous entries · your ballot: 2 of 5","/reveal/the-perfect-loop"],
  ["18:30","RESULTS","Challenge #040 — SMALL THING. BIG SOUND.","Community + Judge Picks revealed tonight","/results/the-perfect-loop"],
  ["FRI 20:00","FINAL CUT","Pilot jury showcase: Five Rooms","Curated final with filmmaker notes","/results/one-room-one-minute-one-thriller"],
  ["SUN 17:00","DROP PREVIEW","Challenge #044 — MAKE IT MOVE.","Brief unlock + team formation","/challenge/make-it-move"],
];
export default function StagePage(){return <div className="page"><header className="challenge-mast"><p className="eyebrow">Programme 34 / IST</p><h1 className="display">THE<br/>STAGE.</h1><p className="lede">Reveals, results and finished work—scheduled with intent. Come for the moment, not an endless feed.</p></header><section><div className="section-head"><h2>On the programme</h2><Radio size={20}/></div><div className="programme">{schedule.map(([time,type,title,description,href],i)=><Link className="programme-row" href={href} key={title}><strong className="programme-time" style={{color:i===0?"var(--red)":"inherit"}}>{time}</strong><div><span className={`status ${i===0?"reveal":""}`}>{type}</span><h3 style={{marginTop:7}}>{title}</h3><p>{description}</p></div><ArrowRight/></Link>)}</div></section><section><div className="section-head"><h2>Recent winning work</h2><Trophy size={20}/></div><div className="proof-grid">{[["COLOUR WITHOUT LIGHT","#039","https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=80"],["FUTURE, USED","#037","https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=700&q=80"],["THE LAST SOUND","#035","https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=700&q=80"]].map(([title,no,cover])=><article className="proof-card" key={title}><div className="proof-cover" style={{backgroundImage:`url(${cover})`}}><span className="award">COMMUNITY PICK</span></div><div className="proof-copy"><h3>{title}</h3><p>{no} · Watch completed highlight</p></div></article>)}</div></section></div>}
