"use client";
import { useState } from "react";
import Link from "next/link";
import { EyeOff, Flag, LockKeyhole, SkipForward, UserRound } from "lucide-react";
import type { Challenge } from "@/lib/types";
import { revealEntries, maya } from "@/lib/demo-data";

type Scores={originality:number;execution:number;entertainment:number};
export function RevealVoting({challenge}:{challenge:Challenge}) {
  const [index,setIndex]=useState(0); const [scores,setScores]=useState<Scores>({originality:0,execution:0,entertainment:0}); const [locked,setLocked]=useState(false); const entry=revealEntries[index%revealEntries.length]; const ready=Object.values(scores).every(Boolean);
  const next=()=>{setIndex(x=>x+1);setScores({originality:0,execution:0,entertainment:0});setLocked(false);};
  return <div className="reveal-shell"><div className="page-narrow"><div className="reveal-top"><div><p className="eyebrow lime">Reveal live</p><strong style={{font:"800 1.3rem var(--display)"}}>CHALLENGE #{challenge.number}</strong></div><span className="stamp">Entry {entry.position} of {entry.total}</span></div><div className="progress-track" style={{borderColor:"white"}}><div className="progress-fill" style={{width:`${entry.position/entry.total*100}%`,background:"var(--lime)"}}/></div><div className="anonymous-note" style={{margin:"12px 0"}}><EyeOff size={17}/><span><strong>Creator hidden for fair voting.</strong><br/>Score the work—not the social signal.</span></div><div className="video-frame"><video key={entry.entryId} src={entry.videoUrl} controls playsInline preload="metadata" aria-label={`Anonymous entry ${entry.position}`}/><span className="entry-stamp">#{String(entry.position).padStart(2,"0")} · 00:{entry.duration}</span></div>
    {!locked?<div className="score-sheet"><p className="eyebrow">Your scorecard</p>{(["originality","execution","entertainment"] as const).map(dimension=><div className="score-row" key={dimension}><label>{dimension}</label>{[1,2,3,4,5].map(value=><button className={`score-dot ${scores[dimension]===value?"selected":""}`} aria-label={`${value} out of 5 for ${dimension}`} aria-pressed={scores[dimension]===value} key={value} onClick={()=>setScores(current=>({...current,[dimension]:value}))}>{value}</button>)}</div>)}<div className="reveal-actions"><button className="button ghost" onClick={next}><SkipForward size={15}/> Skip</button><button className="button blue" disabled={!ready} onClick={()=>setLocked(true)}><LockKeyhole size={16}/> Lock my vote</button></div><button className="button ghost" style={{minHeight:35,marginTop:8,fontSize:10}}><Flag size={13}/> Report unsafe or unplayable</button></div>:
    <div className="identity-reveal"><p className="eyebrow">Vote locked · identity revealed</p><div style={{display:"grid",gridTemplateColumns:"58px 1fr",gap:12,alignItems:"center"}}><img src={maya.avatar} alt="" style={{width:58,height:58,objectFit:"cover",border:"var(--rule)"}}/><div><strong style={{font:"800 1.45rem var(--display)"}}>{maya.displayName}</strong><br/><span>@{maya.handle}</span></div></div><p style={{fontSize:12}}>Your vote is final. Maya cannot see how you scored this entry.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Link className="button" href={`/u/${maya.handle}`}><UserRound size={15}/> View proof</Link><button className="button ink" onClick={next}>Next entry</button></div></div>}
    </div></div>;
}
