"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileVideo, LockKeyhole, RotateCcw, UploadCloud } from "lucide-react";
import type { Challenge } from "@/lib/types";

type Phase="choose"|"uploading"|"review"|"locked";
export function SubmissionFlow({challenge}:{challenge:Challenge}) {
  const [phase,setPhase]=useState<Phase>("choose"); const [progress,setProgress]=useState(0); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string>(); const [error,setError]=useState(""); const [rules,setRules]=useState(false); const [rights,setRights]=useState(false); const input=useRef<HTMLInputElement>(null);
  const choose=(selected?:File)=>{ if(!selected)return; setError(""); if(!challenge.acceptedMimeTypes.includes(selected.type)){setError("Use an MP4, WebM or MOV video.");return;} if(selected.size>challenge.maxBytes){setError(`Video must be under ${Math.round(challenge.maxBytes/1_000_000)} MB.`);return;} setFile(selected);setPreview(URL.createObjectURL(selected));setPhase("uploading");setProgress(8); let n=8; const timer=window.setInterval(()=>{n+=Math.ceil(Math.random()*15);if(n>=100){window.clearInterval(timer);setProgress(100);setTimeout(()=>setPhase("review"),250);}else setProgress(n);},180);};
  if(phase==="locked") return <div className="page-narrow"><div style={{background:"var(--lime)",border:"var(--rule)",padding:"35px 22px",marginTop:45}}><LockKeyhole size={48}/><p className="eyebrow" style={{marginTop:25}}>Entry submitted</p><h1 className="display-sm">HIDDEN.<br/>LOCKED.<br/>READY.</h1><p className="lede">Your entry is safely in Challenge #{challenge.number}. Nobody can browse it before Reveal, and your identity stays out of the vote.</p><div className="panel panel-pad"><span className="status">Submission confirmed</span><p style={{fontSize:13}}>Entry ID: SO-042-MY-8F2<br/>Rules + rights terms v1.1 accepted<br/>Locked at server time</p></div><Link className="button ink full" href="/arcade">Back to Arcade</Link></div></div>;
  return <div className="page-narrow"><Link href={`/challenge/${challenge.slug}`} className="eyebrow"><ArrowLeft size={15}/> Challenge #{challenge.number}</Link><header style={{margin:"25px 0"}}><p className="eyebrow">Create + submit</p><h1 className="display-sm">YOUR TURN.</h1><p className="lede">{challenge.title}</p></header><div className="progress-track"><div className="progress-fill" style={{width:phase==="choose"?"18%":phase==="uploading"?"45%":"78%"}}/></div>
    {phase==="choose"&&<section className="panel panel-pad" style={{marginTop:20}}><div style={{border:"2px dashed var(--ink)",padding:"48px 18px",textAlign:"center",background:"var(--paper)"}}><UploadCloud size={45} strokeWidth={1.5}/><h2 className="display-sm" style={{fontSize:38,marginTop:18}}>DROP YOUR CUT.</h2><p className="muted">{challenge.acceptedMimeTypes.map(x=>x.split("/")[1].toUpperCase()).join(", ")} · max {challenge.maxDurationSeconds}s · {Math.round(challenge.maxBytes/1_000_000)} MB</p><input ref={input} hidden type="file" accept="video/mp4,video/webm,video/quicktime" capture="environment" onChange={e=>choose(e.target.files?.[0])}/><button className="button primary" onClick={()=>input.current?.click()}><FileVideo size={17}/> Choose or record video</button>{error&&<p role="alert" style={{color:"var(--red-dark)",fontWeight:700}}>{error}</p>}</div><div className="notice" style={{marginTop:12}}>Upload goes directly to object storage using a short-lived presigned URL. It can be retried safely without making duplicate entries.</div></section>}
    {phase==="uploading"&&<section className="panel panel-pad" style={{marginTop:20}}><p className="eyebrow">Uploading directly</p><h2 className="display-sm" style={{fontSize:42}}>{progress}%</h2><div className="progress-track" aria-label={`Upload ${progress}% complete`}><div className="progress-fill" style={{width:`${progress}%`}}/></div><p style={{fontSize:13}}>{file?.name}<br/><span className="muted">Keep this tab open. A failed upload can resume safely.</span></p><button className="button ghost" onClick={()=>setPhase("choose")}><RotateCcw size={15}/> Cancel</button></section>}
    {phase==="review"&&<section style={{marginTop:20}}><div className="video-frame" style={{maxHeight:430,margin:"0 auto",borderColor:"var(--ink)"}}><video src={preview} controls playsInline aria-label="Preview of your selected entry"/></div><div className="form-stack panel panel-pad" style={{marginTop:12}}><div className="field"><label htmlFor="caption">Short caption</label><textarea id="caption" maxLength={200} placeholder="Add context without identifying yourself…"/><small>Shown only after creator reveal. 200 characters max.</small></div><label className="checkbox"><input type="checkbox" checked={rules} onChange={e=>setRules(e.target.checked)}/><span><strong>I accept the challenge rules.</strong><br/>Maximum {challenge.maxDurationSeconds}s · {challenge.rules.slice(1).join(" · ")}</span></label><label className="checkbox"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/><span><strong>I accept Content Rights Terms v1.1.</strong><br/>I keep ownership and grant SHOWOUT a narrow licence to host, moderate and showcase this challenge entry.</span></label><label className="checkbox"><input type="checkbox"/><span>This entry includes AI-generated media. <small>(Disclosure is required when applicable.)</small></span></label><button disabled={!rules||!rights} className="button primary full" onClick={()=>setPhase("locked")}><LockKeyhole size={17}/> Submit hidden entry</button><button className="button ghost full" onClick={()=>setPhase("choose")}><RotateCcw size={15}/> Replace video</button></div></section>}
  </div>;
}
