import { NextResponse } from "next/server";
import { z } from "zod";
import { currentUser } from "@/lib/server/auth";
import { rateLimit } from "@/lib/server/rate-limit";
import { store } from "@/lib/server/store";
import { inbox } from "@/lib/demo-data";
const messageInput=z.object({type:z.enum(["TEXT","CHALLENGE_SHARE","PROOF_SHARE","TEAM_INVITATION"]),body:z.string().trim().min(1).max(1500).optional(),referenceId:z.string().optional(),replyToId:z.string().optional(),clientIdempotencyKey:z.string().min(8).max(100)}).refine(v=>v.type!=="TEXT"||Boolean(v.body),"Text body required");
function mayAccess(userId:string,conversationId:string){return userId==="maya"&&inbox.some(item=>item.id===conversationId);}
export async function GET(request:Request,{params}:{params:Promise<{conversationId:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Authentication required"},{status:401});const {conversationId}=await params;if(!mayAccess(user.id,conversationId))return NextResponse.json({error:"Conversation not found"},{status:404});const cursor=new URL(request.url).searchParams.get("cursor");const all=[...store.messages.values()].filter(x=>x.conversationId===conversationId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));const start=cursor?Math.max(0,all.findIndex(x=>x.id===cursor)+1):0;const page=all.slice(start,start+30);return NextResponse.json({messages:page,nextCursor:all[start+30]?.id??null},{headers:{"cache-control":"private, no-store"}});}
export async function POST(request:Request,{params}:{params:Promise<{conversationId:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Authentication required"},{status:401});const {conversationId}=await params;if(!mayAccess(user.id,conversationId)||store.blocks.has(`niko:${user.id}`)||store.blocks.has(`${user.id}:niko`))return NextResponse.json({error:"Conversation not found or blocked"},{status:404});if(!rateLimit(`message:${user.id}`,30,60_000).allowed)return NextResponse.json({error:"Message rate limit reached"},{status:429});const parsed=messageInput.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid message"},{status:400});const key=`${user.id}:${parsed.data.clientIdempotencyKey}`;const existing=store.messages.get(key);if(existing)return NextResponse.json(existing);const message={id:crypto.randomUUID(),conversationId,senderId:user.id,body:parsed.data.body,type:parsed.data.type,referenceId:parsed.data.referenceId,clientKey:parsed.data.clientIdempotencyKey,createdAt:new Date().toISOString()};store.messages.set(key,message);return NextResponse.json(message,{status:201});}
